noticias/urls.py
from django.urls import path
from . import views
from .views import ResultadosFiltro, ResultadoBusqueda

app_name = 'noticias'

urlpatterns = [
        path('welcome/', views.welcome, name='welcome'),
        path('home/', views.home, name='home'),
        path('administrator/', views.administrator, name='administrator'),
        path('historiccontext/', views.historiccontext, name='historiccontext'),
        path('scrape-noticias/', views.scrape_noticias, name='scrape_noticias'),
        path('noticia/<int:noticia_id>/', views.noticia_detail, name='noticia_detail'),
        path('resultados-filtro/', ResultadosFiltro.as_view(), name='resultados_filtro'),
        path('resultados-palabra-clave/', ResultadoBusqueda.as_view(), name='resultados_palabra_clave'),
        path('logout/', views.logout_view, name='logout'),
] 

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noticias.urls', namespace='noticias')),
]

noticias/models.py
from django.db import models

class Noticia(models.Model):
    urlimagen = models.URLField(max_length=200)
    enlace = models.URLField(max_length=200)
    titular = models.CharField(max_length=150)
    autores = models.CharField(max_length=100)
    contenido = models.TextField()
    fextraccion = models.DateTimeField()
    publicada = models.BooleanField(default=False)

    def __str__(self):
        if hasattr(self, 'fuente'):  # Revisar si hay fuentes asociadas
            # Iterar sobre las fuentes relacionadas y obtener el nombre de cada una
            fuentes = ", ".join([fuente.nfuente for fuente in self.fuente.all()])
            return "{} - {}".format(self.titular, fuentes)
        else:
            return self.titular

class Fuente(models.Model):
    nfuente = models.CharField(max_length=50)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='fuente')

    def __str__(self):
        return self.nfuente

noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Noticia, Fuente
from django.views.generic import ListView
from .scrapers import scrape_ukrinform, scrape_bbc, scrape_cnn, scrape_onu
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db.models import Count
from django.contrib.auth.decorators import login_required

# Create your views here.

def welcome(request):
    return render(request, 'welcome.html')

# Definición de una vista basada en clase para mostrar los resultados del filtro
class ResultadosFiltro(ListView):
    model = Noticia
    template_name = 'resultados_filtro.html'
    context_object_name = 'noticias'
    
    # Método para agregar datos adicionales al contexto
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fuentes_seleccionadas = set(self.request.GET.getlist('fuente'))
        context['fuentes_seleccionadas'] = fuentes_seleccionadas
        return context

    # Método para obtener el conjunto de consultas filtradas
    def get_queryset(self):
        fuentes_seleccionadas = self.request.GET.getlist('fuente')
        queryset = Noticia.objects.filter(publicada=True)  # Solo noticias publicadas
        
        if fuentes_seleccionadas:
            query = Q()
            for fuente in fuentes_seleccionadas:
                query |= Q(fuente__nfuente=fuente)
            queryset = queryset.filter(query)
            
        # Ordenar las noticias por fecha de extracción
        queryset = queryset.order_by('-fextraccion')
        
        # Anotar el recuento de noticias publicadas
        queryset = queryset.annotate(publicada_count=Count('publicada', filter=Q(publicada=True)))
        
        return queryset
    
# Definición de una vista basada en clase para mostrar los resultados de la búsqueda por palabra clave
class ResultadoBusqueda(ListView):
    model = Noticia
    template_name = 'resultados_palabra_clave.html'
    context_object_name = 'noticias'

    # Método para obtener el conjunto de consultas filtradas por palabra clave
    def get_queryset(self):
        queryset = Noticia.objects.filter(publicada=True)
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(titular__icontains=query) | queryset.filter(contenido__icontains=query)
        # Ordenar las noticias por fecha de extracción
        queryset = queryset.order_by('-fextraccion')
        return queryset

    # Método para agregar datos adicionales al contexto
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = str(self.request.GET.get('q', ''))
        context['query'] = query
        return context

# Definición de una vista para la página de inicio
def home(request):
    # Obtener todas las noticias ordenadas por fecha de extracción
    noticias = Noticia.objects.filter(publicada=True).order_by('-fextraccion')
    
    # Paginar las noticias
    paginator = Paginator(noticias, 5)  # Mostrar 5 noticias por página
    page = request.GET.get('page')
    try:
        noticias_paginadas = paginator.page(page)
    except PageNotAnInteger:
        # Si el parámetro de la página no es un número, mostrar la primera página
        noticias_paginadas = paginator.page(1)
    except EmptyPage:
        # Si la página está fuera de rango (por encima del número máximo de páginas), mostrar la última página
        noticias_paginadas = paginator.page(paginator.num_pages)

    return render(request, 'home.html', {'noticias_publicadas': noticias_paginadas})

# Definición de una vista para la página de contexto histórico
def historiccontext(request):
    return render(request, 'historic_context.html')

# Definición de una vista para iniciar el proceso de raspado de noticias
def scrape_noticias(request):
    # Lógica para llamar a los scrapers y almacenar las noticias en la base de datos
    scrape_ukrinform()
    scrape_bbc()
    scrape_cnn()
    scrape_onu()
    # Redirecciona a la página de administrador
    return redirect('noticias:administrator')

# Definición de una vista para la página de administrador
@login_required(login_url='noticias:home')
def administrator(request):
    if request.method == 'POST':
        noticia_id = request.POST.get('noticia_id')
        if noticia_id:
            noticia = get_object_or_404(Noticia, id=noticia_id)
            if 'publicar' in request.POST:
                noticia.publicada = True # Marca la noticia como en la página de inicio al publicar
            elif 'despublicar' in request.POST:
                noticia.publicada = False
                noticia.enhome = False  # Desmarca la noticia de la página de inicio al despublicar
            noticia.save()
            return redirect('noticias:administrator')

    # Obtener todas las noticias ordenadas por fecha de extracción
    noticias = Noticia.objects.all().order_by('-fextraccion')

    return render(request, 'administrator.html', {'noticias': noticias})

# Definición de una vista para mostrar el detalle de una noticia específica
def noticia_detail(request, noticia_id):
    # Obtener la noticia específica según su ID
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    return render(request, 'noticia_detail.html', {'noticia': noticia})

# Definición de una vista para cerrar sesión
def logout_view(request):
    return render(request, 'logout.html')

noticias/templates/administrator.html
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mundo Pugna | Administrador</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="shortcut icon" href="{% static 'assets/isotipo.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/administrator.css' %}">
    
</head>

<body>
    <div class="container">
        <div class="container mt-5 custom-container">
            <h1><strong>Panel administrativo</strong></h1>
        </div>

        <div class="table-container">
            <table>
                <colgroup>
                    <col style="width: 10%">
                    <col style="width: 10%">
                    <col style="width: 10%">
                    <col style="width: 20%">
                    <col style="width: 10%">
                    <col style="width: 25%"> <!-- Aumenta el ancho de la columna de contenido -->
                    <col style="width: 10%">
                    <col style="width: 5%"> <!-- Reduce el ancho de la columna de publicada -->
                </colgroup>
                <thead>
                    <tr>
                        <th>URL de la imagen</th>
                        <th>Nombre de la fuente</th>
                        <th>Enlace</th>
                        <th>Titular</th>
                        <th>Autores</th>
                        <th>Contenido</th>
                        <th>Fecha de extracción</th>
                        <th>Publicada</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for noticia in noticias %}
                    <tr>
                        <td><img src="{{ noticia.urlimagen }}" alt="Imagen de la noticia" style="height: auto; max-width: 150px;"></td>
                        <td>
                        {% for fuente in noticia.fuente.all %}
                            <span>{{ fuente.nfuente }}</span>
                        {% endfor %}
                        </td>
                        <td><a href="{{ noticia.enlace }}">{{ noticia.enlace|slice:":20" }}{% if noticia.contenido|length > 20 %}...{% endif %}</a></td>
                        <td>{{ noticia.titular }}</td>
                        <td>{{ noticia.autores }}</td>
                        <td><p>{{ noticia.contenido|slice:":20" }}{% if noticia.contenido|length > 20 %}...{% endif %}</p></td>
                        <td>{{ noticia.fextraccion }}</td>
                        <td>{{ noticia.publicada }}</td>
                        <td>
                            {% if noticia.publicada %}
                                <form class="despublicar-form" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="noticia_id" value="{{ noticia.id }}">
                                    <button type="submit" name="despublicar" class="btn btn-danger despublicar-button">Despublicar</button>
                                </form>
                            {% else %}
                                <form class="publicar-form" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="noticia_id" value="{{ noticia.id }}">
                                    <button type="submit" name="publicar" class="btn btn-primary publicar-button">Publicar</button>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" id="scrape-form" class="form">
                {% csrf_token %}
                <button class="extractor" type="button" id="scrape-button" class="boton">Extraer noticias</button>
            </form>
        </div>
    </div>
</body>

<script>
document.addEventListener('DOMContentLoaded', function () {
    // Agrega un evento de clic al botón de "Scrapear"
    document.getElementById('scrape-button').addEventListener('click', function () {
        // Realiza una solicitud POST al endpoint de tu vista para ejecutar los scrapers
        fetch('{% url "noticias:scrape_noticias" %}', {
            method: 'POST',
            headers: {
                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
            },
        })
        .then(response => {
            // Verifica si la respuesta es exitosa
            if (!response.ok) {
                throw new Error('Hubo un problema al ejecutar los scrapers');
            }
            return response.json();
        })
        .then(data => {
            // Realiza acciones adicionales si es necesario, como mostrar un mensaje de éxito
            console.log('Los scrapers se ejecutaron con éxito');
            // Recargar la página o hacer cualquier otra acción necesaria después de ejecutar los scrapers
            window.location.reload();
        })
        .catch(error => {
            // Maneja cualquier error que ocurra durante el proceso
            console.error('Error al ejecutar los scrapers:', error);
            // Maneja el error si es necesario
        });
    });

    // Selecciona todos los botones de despublicar
    document.querySelectorAll('.despublicar-button').forEach(button => {
        // Agrega un evento de clic a cada botón de despublicar
        button.addEventListener('click', function () {
            // Encuentra el formulario asociado al botón de despublicar
            const form = button.closest('.despublicar-form');
            // Obtiene el ID de la noticia de un campo oculto en el formulario
            const noticiaId = form.querySelector('input[name="noticia_id"]').value;
            // Realiza una solicitud POST al servidor para despublicar la noticia
            fetch('/despublicar-noticia/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                },
                body: JSON.stringify({ 'noticia_id': noticiaId }),
            })
            .then(response => {
                // Verifica si la respuesta es exitosa
                if (!response.ok) {
                    throw new Error('Hubo un problema al despublicar la noticia');
                }
                // Recarga la página después de despublicar la noticia
                window.location.reload();
            })
            .catch(error => {
                // Maneja cualquier error que ocurra durante el proceso
                console.error('Error al despublicar la noticia:', error);
                // Maneja el error si es necesario
            });
        });
    });
});


</script>

</html>

{% endblock %}

noticias/templates/home.html
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mundo Pugna | Inicio</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'assets/isotipo.ico' %}" type="image/x-icon"> 
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    {% include 'snippets/header.html' %}
    {% include 'snippets/logout_button.html' %}
    <div class="container">
        {% include 'snippets/category.html' %}
        {% include 'snippets/navbar.html' %}
        <div class="row-principal justify-content-center">
            <div class="col-lg-12 col-md-12 col-xl-12 col-sm-12 text-center">
                <div class="row">
                    {% for noticia in noticias_publicadas %}
                        {% if forloop.first %}
                            <div class="card-first">
                                <div class="card-img-first">
                                    <a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}">
                                        <img src="{{ noticia.urlimagen }}" alt="Imagen de la noticia" class="image">
                                    </a>
                                </div>
                                <div class="card-content-first">
                                    {% for fuente in noticia.fuente.all %}
                                            <p class="nfuente-first"><strong>{{ fuente.nfuente }}</strong></p>
                                    {% endfor %}
                                    <h1 class="title-first"><strong><a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}">{{ noticia.titular }}</a></strong></h1>
                                    <p class="content-first">{{ noticia.contenido|slice:":200" }}{% if noticia.contenido|length > 200 %}...{% endif %}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            {% for noticia in noticias_publicadas %}
                {% if not forloop.first %}
                    <div class="card">
                        <div class="card-img">
                            <a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}"><img src="{{ noticia.urlimagen }}" alt="Imagen de la noticia" width="350px" height="250px" ></a>
                        </div>
                        <div class="card-content">
                            {% for fuente in noticia.fuente.all %}
                                <p class="nfuente"><strong>{{ fuente.nfuente }}</strong></p>
                            {% endfor %}
                            <h1 class="title" style="text-align: center;"><strong><a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}">{{ noticia.titular }}</strong></a></h1>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if noticias_publicadas.has_previous %}
                    <a href="?page=1" style="text-decoration: none; color: #122330; font-size: 20px;">&laquo; Primera</a>
                    <a href="?page={{ noticias_publicadas.previous_page_number }}" style="text-decoration: none; color: #122330; font-size: 20px;"><strong>Anterior |</strong></a>
                {% endif %}
    
                <span class="current" style="font-size: 20px;">
                    Página {{ noticias_publicadas.number }} de {{ noticias_publicadas.paginator.num_pages }}
                </span>
    
                {% if noticias_publicadas.has_next %}
                    <a href="?page={{ noticias_publicadas.next_page_number }}" style="text-decoration: none; color: #122330; font-size: 20px;"><strong>| Siguiente</strong></a>
                    <a href="?page={{ noticias_publicadas.paginator.num_pages }}" style="text-decoration: none; color: #122330; font-size: 20px;"> Última &raquo;</a>
                {% endif %}
            </span>
        </div>
            <form method="GET" action="{% url 'noticias:resultados_filtro' %}" class="filter-form">
                <fieldset class="filter-fieldset">
                    <legend class="filter-legend" style="text-align: center;">Seleccionar fuente:</legend>
                    <select name="fuente" multiple class="filter-select">
                        <option value="CNN Español">CNN</option>
                        <option value="BBC">BBC</option>
                        <option value="ONU">ONU</option>
                        <option value="Ukrinform">Ukrinform</option>
                    </select>
                </fieldset>
                <button type="submit" class="filter-button">Filtrar</button>
            </form>
        <form method="GET" action="{% url 'noticias:resultados_palabra_clave' %}">
            <input type="text" name="q" placeholder="Buscar palabra clave..." style="border-radius: 5px; border-color: #122330; padding: 10px; border-width: 3px; border-style: solid; background-color: transparent;">
            <button type="submit">Buscar</button>
        </form>
    </div>
    {% include 'snippets/footer.html' %}

</body>
</html>

{% endblock %}

noticias/templates/logout.html
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mundo Pugna | Salida</title>
    <link rel="stylesheet" href="{% static 'styles/logout.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/isotipo.ico' %}" type="image/x-icon"> 
</head>
<body>
    {% include 'snippets/header_welcome.html' %}
    <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 25vh;">
        <h1><strong>¡Gracias por visitarnos!</strong></h1>
        <p>¿Necesitas volver al inicio? <strong>¡Hazlo con un clic!</strong></p>
    </div>
    
    <div class="row justify-content-center container-logout">
        <div class="col-md-12">
            <a href="{% url 'noticias:home' %}" class="boton">Volver al inicio</a>
        </div>
    </div>
    {% include 'snippets/footer.html' %}
</body>
</html>

{% endblock %}

noticias/templates/resultados_filtro.html
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Mundo Pugna | Resultados del filtro</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'assets/isotipo.ico' %}" type="image/x-icon"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/resultados_filtro.css' %}">
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
</head>
<body>
    {% include 'snippets/header.html' %}
    {% include 'snippets/logout_button.html' %}
<div class="container">
    <div class="container mt-5 custom-container">
        <h1><strong>Resultados del filtro</strong></h1>
    </div>
    <p style="font-size: 20px;">Resultados por:</p>
    <ul style="list-style-type: disc; font-size: 20px;">
        {% for fuente in fuentes_seleccionadas %}
            <li><strong>{{ fuente }}</strong></li>
        {% endfor %}
    </ul>
    <p style="font-size: 20px;">Resultados encontrados: <strong>{{ noticias.count }}</strong></p>
    <div class="row">
        {% for noticia in noticias %}
            {% if noticia.publicada %}
            <div class="card">
                <div class="card-img">
                    <a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}">
                        <img src="{{ noticia.urlimagen }}" alt="Imagen de la noticia" width="350px" height="250px">
                    </a>
                </div>
    
                <div class="card-content">
                    {% for fuente in noticia.fuente.all %}
                        <p class="nfuente"><strong>{{ fuente }}</strong></p>
                    {% endfor %}
                    <h1 class="title" style="text-align: center;">
                        <strong><a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}">{{ noticia.titular }}</a></strong>
                    </h1>
                    <p class="content">{{ noticia.contenido|slice:":200" }}{% if noticia.contenido|length > 200 %}...{% endif %}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
    
    


{% include 'snippets/footer.html' %}
</body>
</html>

{% endblock %}

noticias/templates/resultados_palabra_clave.html
{% load static %}

{% load filters %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mundo Pugna | Resultados de la búsqueda por palabra clave</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'assets/isotipo.ico' %}" type="image/x-icon"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/resultado_palabra_clave.css' %}">
</head>
<body>
    {% include 'snippets/header.html' %}
    {% include 'snippets/logout_button.html' %}

    <div class="container">
        <div class="container mt-5 custom-container">
            <h1 class="title mb-5"><strong>Resultados por palabra clave</strong></h1>
        </div>
        {% if object_list %}
        <ul style="list-style-type: none;">
            {% for noticia in object_list %}
            <li>
                <h2><a href="{% url 'noticias:noticia_detail' noticia_id=noticia.id %}" style="text-decoration: none; color: #122330;"><strong>{{ noticia.titular|highlight:query }}</strong></a></h2>
                <p>{{ noticia.contenido|highlight:query }}</p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No se encontraron resultados.</p>
        {% endif %}
    </div>

    {% include 'snippets/footer.html' %}
</body>
</html>

{% endblock %}

noticias/templates/snippets/category.html
<style>
    .category{
        margin-bottom: 40px;
    }

    h4 {
        text-align: center;
        font-weight: bold;
        color:#122330;
    }

</style>

<h4 class="category">CONFLICTO RUSIA-UCRANIA</h4>

noticias/templates/snippets/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'styles/footer.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

<footer>
   <div class="footer-icons">
    <a href="https://www.facebook.com/profile.php?id=61556601659384" target="_blank">
        <i class='fa-brands fa-facebook-f'></i>
    </a>
    <a href="https://www.instagram.com/mundopugna/" target="_blank">
        <i class='fa-brands fa-instagram'></i>
    </a>
    <a href="https://twitter.com/MundoPugna" target="_blank">
        <i class='fa-brands fa-x-twitter'></i>
    </a>
    </div>
    <p>Derechos de autor ™ 2024 Mundo Pugna</p>
</footer>

noticias/templates/snippets/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'styles/header.css' %}">

<header>
    <a href="{% url 'noticias:home' %}">
        <img src="{% static 'images/LOGOTYPE_MUNDO_PUGNA_VERTICAL_NARANJA_BLANCO.png' %}" alt="Logotipo de Mundo Pugna"  width="300px" height="300px">
    </a>

</header>

noticias/templates/snippets/header_welcome.html
{% load static %}

<link rel="stylesheet" href="{% static 'styles/header.css' %}">

<header>
        <img src="{% static 'images/LOGOTYPE_MUNDO_PUGNA_VERTICAL_NARANJA_BLANCO.png' %}" alt="Logotipo de Mundo Pugna"  width="300px" height="300px">
</header>

noticias/templates/snippets/logout_button.html
{% load static %}

<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" href="{% static 'styles/logout.css' %}">

<a href="{% url 'noticias:logout' %}" class="logout-icon" title="Salir">
    <i class='bx bxs-exit' style="font-size: 50px; color: #F49D21;"></i>
</a>

noticias/templates/snippets/navbar.html
{% load static %}

<link rel="stylesheet" href="{% static 'styles/navbar.css' %}">

<div class="container-fluid">
<nav class="navbar navbar-expand-lg" style="background-color: #122330; border-radius: 10px;">
    <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'noticias:home' %}" id="noticias">Noticias</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'noticias:historiccontext' %}" id="contexto-historico">Contexto histórico</a>
            </li>
        </ul>
    </div>
</nav>
</div>